[global]
index-url = https://pypi.tuna.tsinghua.edu.cn/simple
extra-index-url = https://download.pytorch.org/whl/cu124
trusted-host =
    pypi.tuna.tsinghua.edu.cn
    mirrors.aliyun.com
    download.pytorch.org
